# configurations
dataset_cfg:
    OfficeHome:
        name: OfficeHome
        path: /tmp2/chu0802/data/OfficeHome
        text_path: /tmp2/chu0802/data/OfficeHome/text
        num_classes: 65
        domains:
                - Art
                - Clipart
                - Product
                - RealWorld
    Office31:
        name: Office31
        path: /tmp2/chu0802/data/Office31
        text_path: /tmp2/chu0802/data/Office31/text
        num_classes: 31
        domains:
                - amazon
                - dslr
                - webcam
    DomainNet:
        name: DomainNet
        path: /tmp2/chu0802/data/DomainNet
        text_path: /tmp2/chu0802/data/DomainNet/text
        num_classes: 126
        domains:
                - clipart
                - painting
                - real
                - sketch
